#!/bin/bash
if [ -z $1 ]
then
   CONTAINER_NAME_STRING=""
else
   CONTAINER_NAME_STRING="--name=$1"
fi

xhost +local:docker
docker run \
  -ti \
  --network=host \
  -e DISPLAY=$DISPLAY \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  --privileged \
  $CONTAINER_NAME_STRING \
  -v ~:/root/home \
  --ipc host \
  x11_base
