#!/bin/bash
xhost +local:docker
docker run \
-ti \
--network=host \
-e DISPLAY=$(ifconfig en0 | grep inet | awk '$1=="inet" {print $2}'):0 \
-v /tmp/.X11-unix:/tmp/.X11-unix \
--privileged \
-v ~:/root/home \
--ipc host x11_mac
